name: Update Graypaper

on:
  workflow_dispatch:
  schedule:
    - cron: "38 13 * * *" # using an arbitrary time to avoid high traffic

jobs:
  check_for_updates:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    outputs:
      has_updates: ${{steps.remote_release.outputs.VERSION != steps.local_release.outputs.VERSION}}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: What's the latest graypaper version?
      id: remote_release
      run: |
        echo "VERSION=$(gh api /repos/gavofyork/graypaper/releases/latest | jq -r '.tag_name')" >> "$GITHUB_OUTPUT"
    - name: What's the version we're using?
      id: local_release
      run: |
        cd graypaper
        echo "VERSION=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"
  update:
    name: Update
    runs-on: ubuntu-latest
    needs: check_for_updates
    permissions:
      contents: write
      pull-requests: write
    env:
      GH_TOKEN: ${{ github.token }}
    if: needs.check_for_updates.outputs.has_updates
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Get latest graypaper and create a pull request
        id: graypaper_update
        run: |
          git submodule update --remote
          scripts/build-pdf-docker.sh
          cd graypaper
          echo "VERSION=v$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"
          cd ..
      - name: Commit changes to the main branch
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Bump to ${{steps.graypaper_update.outputs.VERSION}}
          tag: ${{steps.graypaper_update.outputs.VERSION}}
       